baseURL = 'http://oderberg-mark.de/'
languageCode = 'de-de'
title = 'Oderberg/Mark'

assetdir = 'static'

[taxonomies]
  tag = "tags"
  category = "categories"
  person = "personen"

[markup.goldmark.renderer]
  unsafe = true

enableGitInfo = true

[menu]
  [[menu.main]]
  name = 'Kategorien und Stichw√∂rter'
  url = '/tags'
  weight = 100